[project]
name = "pulumi_state_splitter"
version = "0.1.0"
description = "Manipulates a Pulumi state file to make it more VCS friendly"
authors = [{ name = "Filip Zyzniewski", email = "filip.zyzniewski@gmail.com" }]
requires-python = ">=3.11,<4"
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pydantic>=2.5.3,<3",
    "pyyaml>=6.0.1,<7",
    "click>=8.1.7,<9",
    "style-tests",
]

[project.scripts]
pulumi_state_splitter = "pulumi_state_splitter:cli"

[dependency-groups]
dev = [
    "coverage>=7.3.4,<8",
    "pulumi>=3.99.0,<4",
    "pulumi-command>=0.10.0",
    "typeguard>=4.1.5,<5",
    "parameterized>=0.9.0,<0.10",
]

[tool.uv]
default-groups = "all"

[tool.uv.sources]
style-tests = { git = "https://github.com/house-reliability-engineering/python.git", subdirectory = "style_tests" }

[tool.uv.build-backend]
module-root = ""

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
