on:
  push:
    paths: utilities/pulumi_state_splitter/**

jobs:
  tests:
    runs-on: ubuntu-latest
    name: pulumi_state_splitter tests
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          cache: poetry
          cache-dependency-path: utilities/pulumi_state_splitter/poetry.lock
          python-version: '3.11'
      - run: ./utilities/pulumi_state_splitter/run-tests.sh

